# Generated by Django 5.0.1 on 2024-02-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_comment_comments_rename_post_comments_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(default='jslkdfjlafjsldfjlskfjd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='steps',
            field=models.TextField(default='salkdfjalkdfjalfjdlfa'),
            preserve_default=False,
        ),
    ]
