# Generated by Django 5.0.1 on 2024-02-03 10:33

from django.conf import settings
from django.db import migrations, models


def delete_duplicate_likes(apps, schema_editor):
    Likes = apps.get_model("recipes", "Likes")
    Recipes = apps.get_model("recipes", "Recipes")  # Get the Recipe model
    for recipe in Recipes.objects.all():
        likes = Likes.objects.filter(recipe=recipe).order_by("user", "created_date")
        likes = likes.values("user").annotate(min_id=models.Min("id")).values("min_id")
        Likes.objects.filter(recipe=recipe).exclude(id__in=likes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipes_is_verified_alter_recipes_ingredients_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_likes),
        migrations.RemoveConstraint(
            model_name="recipes",
            name="imported_recipe_requires_description_ingredients",
        ),
        migrations.AlterUniqueTogether(
            name="likes",
            unique_together={("user", "recipe")},
        ),
        migrations.AddConstraint(
            model_name="recipes",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("author__isnull", True), ("is_imported_recipe", True)),
                    ("is_imported_recipe", False),
                    _connector="OR",
                ),
                name="user_created_recipe_requires_author",
            ),
        ),
    ]
