# Generated by Django 5.0.1 on 2024-02-05 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipes_imported_recipe_requires_description_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.comments'),
        ),
    ]
