# Generated by Django 5.0.1 on 2024-02-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_comments_parent_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent_comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='recipes.comments'),
        ),
    ]
