# Generated by Django 5.0.1 on 2024-02-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('professional', 'Professional'), ('user', 'User')], default='user', max_length=12),
        ),
    ]
